Contemplanto projeto com upgrade de frameworks
portabilis/i-diario-app pull request #4
Opened 2024-09-16 02:20 UTC by msoares94

Esse PR contempla a atualização do projeto com as versões mais recentes do Ionic e Angular

2024-09-16 02:23 UTC, msoares94 commented
@edersoares conforme prometido, segue o PR com o upgrade do projeto para contemplar as versões mais recentes dos frameworks (Ionic e Angular)

2024-09-16 12:58 UTC, edersoares commented
@msoares94 que contribuição incrível! Muito obrigado por isso.

Vamos adicionar no nosso fluxo de testes internos e mantenho você informado!

Incrível!

2024-09-17 13:17 UTC, edersoares requested changes
@msoares94 fiz alguns testes e já pude notar alguns ajustes, vou fazendo por partes para que possam ser corrigidos gradativamente.

Sugiro termos nos arquivos `environment.ts` e `environment.prod.ts` variáveis de ambiente que sejam mais fáceis de substituir ao invés de mexer diretamente no código.

2024-09-17 13:17 UTC, edersoares commented on src/app/sign-in/sign-in.page.ts
> +    { name: 'Treinamento', url: 'https://treinamento.idiario.net.br', support_url: '' }
Isso pode ser um buscado de um arquivo `.ts` padrão e caso não exista podemos usar um fallback para outro arquivo com:

```suggestion
    { name: 'i-Diário', url: 'http://localhost:3000', support_url: '' }
```

2024-09-17 13:17 UTC, edersoares commented on src/app/services/offline_data_persistence/unities_persister.ts
> +    this.unities.getOnlineUnities(148).subscribe(res => {
ID do usuário fixado, tem que ser pego do contexto do usuário logado e salvar no storage, o que não está sendo feito.

2024-09-17 13:17 UTC, edersoares commented on src/app/sign-in/sign-in.page.ts
> +      this.messages.showToast('Sem conexão!', 1000, 'top');
Essa mensagem está sempre sendo exibida.

2024-10-09 19:19 UTC, leoholiveira commented
@msoares94 ótima contribuição. Muito boa a sua iniciativa e achei excelente essa contribuição.

Sobre o app, notei alguns pontos que chamou minha atenção:

- As versões das bibliotecas "capacitor" encontram uma vulnerabilidade que permite injection;

<img width="238" alt="image" src="https://github.com/user-attachments/assets/d7a1ab81-4b95-49de-b306-3fdcab305ea4">

- Quando efetuei o login com um usuário e depois desloguei e entrei com outro, o app mantem os dados do usuário que foi efetuado o login pela primeira vez (acredito que seja um problema de cache);

- O backend retornou dados de frequência, porém no app não efetou o carregamento da lista (pode ser algum parametrô que não consegui encontrar).

![image](https://github.com/user-attachments/assets/0f967deb-01ad-4b3b-97ed-60d05da78e58)

Sobre a atualização no geral, está muito boa mesmo, agradeço novamente.

2024-11-01 20:10 UTC, msoares94 commented
> @msoares94 ótima contribuição. Muito boa a sua iniciativa e achei excelente essa contribuição.
> 
> Sobre o app, notei alguns pontos que chamou minha atenção:
> 
>     * As versões das bibliotecas "capacitor" encontram uma vulnerabilidade que permite injection;
> 
> 
> <img alt="image" width="238" src="https://private-user-images.githubusercontent.com/95356773/375099248-d7a1ab81-4b95-49de-b306-3fdcab305ea4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0OTIxMTYsIm5iZiI6MTczMDQ5MTgxNiwicGF0aCI6Ii85NTM1Njc3My8zNzUwOTkyNDgtZDdhMWFiODEtNGI5NS00OWRlLWIzMDYtM2ZkY2FiMzA1ZWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDIwMTAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlNjhhODQwYTUwZmY1YWNmN2YxMDMwZWMzYjM0Zjk0MjkxMjU2ZjhhOTAwNmI2MzA4YTE0MjllYWNjZDgwYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.S6vtTdURyjxDWnOClvWNu3lw_q8U97UTFa0P4kgsVCQ">
> 
>     * Quando efetuei o login com um usuário e depois desloguei e entrei com outro, o app mantem os dados do usuário que foi efetuado o login pela primeira vez (acredito que seja um problema de cache);
> 
>     * O backend retornou dados de frequência, porém no app não efetou o carregamento da lista (pode ser algum parametrô que não consegui encontrar).
> 
> 
> ![image](https://private-user-images.githubusercontent.com/95356773/375100603-0f967deb-01ad-4b3b-97ed-60d05da78e58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0OTIxMTYsIm5iZiI6MTczMDQ5MTgxNiwicGF0aCI6Ii85NTM1Njc3My8zNzUxMDA2MDMtMGY5NjdkZWItMDFhZC00YjNiLTk3ZWQtNjBkMDVkYTc4ZTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDIwMTAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0MTI3MzdjOGNjOTBlMmIxZjQ0OTdhMzcxYTE1NDkyMjNlY2I1YzY0MDQyYjVlZTNjMzI4MzRkMTVlMjE4MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9tKpoT3XF7GSu8wyaLRBO0ccpSQBnvACQ7WXEgnZfxE)
> 
> Sobre a atualização no geral, está muito boa mesmo, agradeço novamente.

Corrigido, obrigado pelos apontamentos

2024-12-19 23:43 UTC, msoares94 commented
@edersoares, @leoholiveira e mais quem for interessado, vamos unir esforços para fazermos esse PR ser aceito, a versão atual do Android para a versão 1.1 já não é mais aceita pelas lojas de aplicativo.

2024-12-26 10:25 UTC, ferox commented
@edersoares Tendo em vista qie todos os apontamentos e correções foram realizadas esta PR está apta para entrar no repositório.

Há algo a mais que precisa ser alterado?

@leoholiveira Chegou a testar o login e a frequência após os ajustes?

2025-01-08 13:59 UTC, edersoares commented
@msoares94 obrigado novamente pela contribuição.

Eu vou tocar este projeto diretamente, já estou fazendo melhorias e refatorações para que seja possível mantermos o aplicativo atualizado.

Nós vamos precisar de apoio nos testes então peço a todos os interessados que quiserem fazer parte destes testes me avisem.

Nós fizemos a atualização para o Ionic 8 e Angular 18 (19 não está permitindo build pra Android) e iniciei a reescrita do core da sincronização que está uma bagunça. Minha ideia é ter uma versão disponível para testes na semana que vem.

2025-01-08 14:04 UTC, msoares94 commented
Olá @edersoares que bom que pude ajudar!
Fico disponível como sempre estou para tratar desses assuntos.

Pode me colocar como interessado nos testes também.

2025-01-17 17:14 UTC, edersoares commented
@msoares94 muito obrigado pela contribuição e esforços em atualizar o aplicativo.

Eu fiz uma análise geral e vamos aproveitar este PR para ser base de uma refatoração da regra de negócio, com isso já vou fazer o merge, porém o aplicativo não está estável ainda. 

Na semana que vem quero publicar mais PRs com as evolução (a nível de regra de negócio e refatorações) que fizemos internamente.

Novamente, obrigado, Marcos!

2025-01-17 17:14 UTC, merged

2025-01-17 17:36 UTC, msoares94 commented
@edersoares que notícia maravilhosa, fico feliz em saber que estamos evoluíndo!
Acredito que o PR como base teremos novas contribuições